### ISSUE TITLE
YOLOv8 rebuilding CUDA engine not finishing

### ISSUE THREAD

**Issue by leon-seidel** [NVIDIA-ISAAC-ROS/isaac_ros_object_detection#37]
When executing the commands from the Quickstart the following comes up and inference never seems to start:

`2024-02-27 14:15:34.115 WARN  /data/jenkins/ros/workspace/ly_debian-compatible-release-2.1/isaac_ros-dev/ros_ws/src/isaac_ros_dnn_inference/isaac_ros_tensor_rt/gxf/tensor_rt/tensor_rt_inference.cpp@278: Rebuilding CUDA engine /tmp/yolov8s.plan (forced by config). Note: this process may take up to several minutes.`

I waited over an hour on an Orin NX without any further messages. As this is probably the TensorRT conversion I also tried exporting to TensorRT with `yolo export model=yolov8s.pt format='engine'` outside the container, which works just fine. However, using the resulting TensorRT model inside the container did not work as well. Any ideas on this?

**Comment by jaiveersinghNV** [comment]
Hi @leon-seidel ,

Could you please provide the full logs up to and including the message you sent? It's possible there was a failure earlier in the logs that led to a different node in the launch graph failing, which is why you don't see any further messages.

Also, can you check if any engine plan file is created at the end of that waiting period? Or is `/tmp/` still empty?

When you say that the plan created outside the container didn't work "as well" inside the container, do you have a specific metric you're using, or any observations about how the performance is different?

This information will help us help you. Thanks!

**Comment by leon-seidel** [comment]
Thanks for your answer and sorry for the late reply! Looking at the full logs show that the problem seems to be related to `lipnvvpi`, as the `tensor_rt_container` doesn't even start.

```
[ERROR] [1709216981.120842565] [tensor_rt_container]: Failed to load library: Could not load library dlopen error: /opt/nvidia/vpi2/lib64/libnvvpi.so.2: version `VPI_2.3' not found (required by /opt/ros/humble/lib/libisaac_ros_nitros_image_type.so), at /tmp/binarydeb/ros-humble-rcutils-5.1.4/src/shared_library.c:99
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'dnn_image_encoder' of type 'nvidia::isaac_ros::dnn_inference::DnnImageEncoderNode' in container '/tensor_rt_container': Failed to load library: Could not load library dlopen error: /opt/nvidia/vpi2/lib64/libnvvpi.so.2: version `VPI_2.3' not found (required by /opt/ros/humble/lib/libisaac_ros_nitros_image_type.so), at /tmp/binarydeb/ros-humble-rcutils-5.1.4/src/shared_library.c:99
```
Regarding the other questions:
There is a plan file created in `/tmp/` and with "as well" I meant that it's not working at all, either.
We are using Jetpack 5.1.1 for this.

[Full logs are here](https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_object_detection/files/14481508/yolo-node-full_log.txt)

**Comment by leon-seidel** [comment]
Update: Upgrading to Jetpack 5.1.2 fixed this
